name: 🆕 Feature
description: Request a new feature
title: "[FEATURE] <title>"
labels: [enhancement]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the feature you are requesting.
    options:
    - label: I have searched the existing issues
      required: true
- type: textarea
  attributes:
    label: Feature description
    description: Dscribe what you would like to see in `russ`.
  validations:
    required: true
